from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class ChargingAreaConfig:
    """Charging-pad geometry and the return-to-charge flight policy.

    ``pad_positions`` stores the vehicle-center pose used once a drone has
    landed. The compact prototype does not model contact dynamics; after the
    landing guard is met the vehicle is snapped by a few centimetres at most to
    its pad pose and held there with the motors off. Before that instant the
    return flight is generated by the smooth acceleration policy below.
    """

    pad_positions: np.ndarray
    approach_height: float = 0.85
    approach_radius: float = 0.45
    maximum_speed: float = 1.25
    maximum_descent_speed: float = 0.55
    velocity_gain: float = 2.2
    maximum_acceleration: float = 3.5
    landing_position_tolerance: float = 0.09
    landing_speed_tolerance: float = 0.18
    platform_padding: float = 0.32

    def __post_init__(self) -> None:
        pads = np.asarray(self.pad_positions, dtype=float)
        if pads.ndim != 2 or pads.shape[1] != 3:
            raise ValueError("pad_positions must have shape (num_robots, 3).")
        if not np.all(np.isfinite(pads)):
            raise ValueError("pad_positions must be finite.")
        for name in (
            "approach_height",
            "approach_radius",
            "maximum_speed",
            "maximum_descent_speed",
            "velocity_gain",
            "maximum_acceleration",
            "landing_position_tolerance",
            "landing_speed_tolerance",
            "platform_padding",
        ):
            if float(getattr(self, name)) <= 0.0:
                raise ValueError(f"{name} must be positive.")
        object.__setattr__(self, "pad_positions", pads)

    def pad(self, robot: int) -> np.ndarray:
        return self.pad_positions[int(robot)].copy()

    def acceleration_command(
        self,
        position: np.ndarray,
        velocity: np.ndarray,
        robot: int,
    ) -> np.ndarray:
        """Return a bounded acceleration command for a returning drone.

        The drone first translates toward a point above its pad. Once the
        horizontal error is small, the reference descends to the pad. A smooth
        saturated desired velocity prevents the return controller from asking
        the low-level attitude loop for aggressive accelerations.
        """
        position = np.asarray(position, dtype=float).reshape(3)
        velocity = np.asarray(velocity, dtype=float).reshape(3)
        pad = self.pad(robot)

        horizontal_error = float(np.linalg.norm(position[:2] - pad[:2]))
        target = pad.copy()
        if horizontal_error > self.approach_radius:
            target[2] = max(pad[2] + self.approach_height, position[2] * 0.65)

        error = target - position
        distance = float(np.linalg.norm(error))
        if distance <= 1e-12:
            desired_velocity = np.zeros(3)
        else:
            # tanh gives a smooth linear law near the target and a speed bound
            # far away. The vertical descent speed is limited separately.
            speed = self.maximum_speed * np.tanh(distance / max(self.approach_radius, 1e-9))
            desired_velocity = speed * error / distance
            desired_velocity[2] = max(
                desired_velocity[2],
                -self.maximum_descent_speed,
            )

        acceleration = self.velocity_gain * (desired_velocity - velocity)
        norm = float(np.linalg.norm(acceleration))
        if norm > self.maximum_acceleration:
            acceleration *= self.maximum_acceleration / norm
        return acceleration

    def landed(
        self,
        position: np.ndarray,
        velocity: np.ndarray,
        robot: int,
    ) -> bool:
        position = np.asarray(position, dtype=float).reshape(3)
        velocity = np.asarray(velocity, dtype=float).reshape(3)
        return (
            np.linalg.norm(position - self.pad(robot)) <= self.landing_position_tolerance
            and np.linalg.norm(velocity) <= self.landing_speed_tolerance
        )
